# Generated by Django 4.1.4 on 2022-12-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=221)),
                ('phone', models.CharField(max_length=18)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзыв',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=333, verbose_name='заголовок')),
                ('title_ru', models.CharField(max_length=333, null=True, verbose_name='заголовок')),
                ('title_uz', models.CharField(max_length=333, null=True, verbose_name='заголовок')),
                ('title_en', models.CharField(max_length=333, null=True, verbose_name='заголовок')),
                ('content', models.TextField(verbose_name='содержание')),
                ('content_ru', models.TextField(null=True, verbose_name='содержание')),
                ('content_uz', models.TextField(null=True, verbose_name='содержание')),
                ('content_en', models.TextField(null=True, verbose_name='содержание')),
                ('image', models.ImageField(upload_to='news/', verbose_name='изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=221, verbose_name='название')),
                ('name_ru', models.CharField(max_length=221, null=True, verbose_name='название')),
                ('name_uz', models.CharField(max_length=221, null=True, verbose_name='название')),
                ('name_en', models.CharField(max_length=221, null=True, verbose_name='название')),
                ('subtitle', models.CharField(max_length=221, verbose_name='подзаголовок')),
                ('subtitle_ru', models.CharField(max_length=221, null=True, verbose_name='подзаголовок')),
                ('subtitle_uz', models.CharField(max_length=221, null=True, verbose_name='подзаголовок')),
                ('subtitle_en', models.CharField(max_length=221, null=True, verbose_name='подзаголовок')),
                ('date', models.CharField(max_length=100, verbose_name='Дата')),
                ('date_ru', models.CharField(max_length=100, null=True, verbose_name='Дата')),
                ('date_uz', models.CharField(max_length=100, null=True, verbose_name='Дата')),
                ('date_en', models.CharField(max_length=100, null=True, verbose_name='Дата')),
                ('price', models.PositiveIntegerField(verbose_name='цена')),
                ('image', models.ImageField(upload_to='offers/', verbose_name='изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Специальные предложения',
                'verbose_name_plural': 'Специальные предложения',
            },
        ),
        migrations.CreateModel(
            name='Useful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=222, verbose_name='заголовок')),
                ('title_ru', models.CharField(max_length=222, null=True, verbose_name='заголовок')),
                ('title_uz', models.CharField(max_length=222, null=True, verbose_name='заголовок')),
                ('title_en', models.CharField(max_length=222, null=True, verbose_name='заголовок')),
                ('content', models.TextField(verbose_name='содержание')),
                ('content_ru', models.TextField(null=True, verbose_name='содержание')),
                ('content_uz', models.TextField(null=True, verbose_name='содержание')),
                ('content_en', models.TextField(null=True, verbose_name='содержание')),
            ],
            options={
                'verbose_name': 'ПОЛЕЗНАЯ ИНФОРМАЦИЯ',
                'verbose_name_plural': 'ПОЛЕЗНАЯ ИНФОРМАЦИЯ',
            },
        ),
    ]
