# Generated by Django 4.1.4 on 2022-12-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useful',
            options={'verbose_name': 'Полезная информация', 'verbose_name_plural': 'Полезная информация'},
        ),
        migrations.AddField(
            model_name='offer',
            name='price_dollar',
            field=models.PositiveIntegerField(default=1, verbose_name='доллар'),
            preserve_default=False,
        ),
    ]
