# Generated by Django 4.1.4 on 2022-12-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_useful_options_offer_price_dollar'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content_oz',
            field=models.TextField(null=True, verbose_name='содержание'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_oz',
            field=models.CharField(max_length=333, null=True, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='offer',
            name='date_oz',
            field=models.CharField(max_length=100, null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='offer',
            name='name_oz',
            field=models.CharField(max_length=221, null=True, verbose_name='название'),
        ),
        migrations.AddField(
            model_name='offer',
            name='subtitle_oz',
            field=models.CharField(max_length=221, null=True, verbose_name='подзаголовок'),
        ),
        migrations.AddField(
            model_name='useful',
            name='content_oz',
            field=models.TextField(null=True, verbose_name='содержание'),
        ),
        migrations.AddField(
            model_name='useful',
            name='title_oz',
            field=models.CharField(max_length=222, null=True, verbose_name='заголовок'),
        ),
    ]
