# Generated by Django 4.1.4 on 2022-12-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_news_content_oz_news_title_oz_offer_date_oz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='content_oz',
            new_name='content_ky',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title_oz',
            new_name='title_ky',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='date_oz',
            new_name='date_ky',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='name_oz',
            new_name='name_ky',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='subtitle_oz',
            new_name='subtitle_ky',
        ),
        migrations.RenameField(
            model_name='useful',
            old_name='content_oz',
            new_name='content_ky',
        ),
        migrations.RenameField(
            model_name='useful',
            old_name='title_oz',
            new_name='title_ky',
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='created_at',
            field=models.DateField(),
        ),
    ]
