# Generated by Django 4.1.5 on 2023-01-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('own_image', models.FileField(upload_to='own_images/')),
                ('passport_image', models.FileField(upload_to='passports/')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('date_birth', models.DateField()),
                ('passport_data', models.CharField(max_length=15)),
                ('price', models.PositiveBigIntegerField()),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
